# Generated by Django 4.1 on 2022-08-10 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("sobrenome", models.CharField(max_length=100)),
                (
                    "cargo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PP", "Desenvolvedor Python Pleno"),
                            ("PJ", "Desenvolvedor Python Júnior"),
                            ("JS", "Desenvolvedor Java Script Pleno"),
                            ("C", "CEO"),
                            ("RC", "Tech Recruiter"),
                            ("RS", "Desenvolvedor React Sênior"),
                            ("O", "Outros"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("empresa", models.ManyToManyField(to="empresas.empresa")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
