# Generated by Django 3.2.15 on 2022-08-12 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20220811_2218'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionario',
        ),
    ]
