# Generated by Django 3.2.15 on 2022-08-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vagas',
            options={'verbose_name': 'vaga', 'verbose_name_plural': 'vagas'},
        ),
        migrations.AlterField(
            model_name='vagas',
            name='nome',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='vagas',
            table='vagas',
        ),
    ]
