# Generated by Django 3.2.15 on 2022-08-12 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_qtd_funcionario'),
        ('vagas', '0002_auto_20220811_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
