# Generated by Django 3.2.15 on 2022-08-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_vagas_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='senioridade',
            field=models.CharField(blank=True, choices=[('J', 'Junior'), ('P', 'Pleno'), ('S', 'Senior'), ('E', 'Especialista')], max_length=20, null=True),
        ),
    ]
