# Generated by Django 3.2.15 on 2022-08-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_vagas_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
