# Generated by Django 3.2.15 on 2022-08-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0007_alter_vagas_faixa_salarial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='status',
            field=models.BooleanField(default=True, help_text='Status da vaga'),
        ),
    ]
