# Generated by Django 4.1 on 2022-08-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0008_vagas_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vagas",
            name="escolaridade",
        ),
        migrations.AddField(
            model_name="vagas",
            name="escolaridade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="vagas.escolaridadevaga",
            ),
            preserve_default=False,
        ),
    ]
