# Generated by Django 3.2.15 on 2022-08-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0009_remove_vagas_escolaridade_vagas_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
