# Generated by Django 3.2.15 on 2022-08-17 14:31

from django.db import migrations, models
import vagas.models.models_vagas


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0010_alter_vagas_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='image',
            field=models.ImageField(blank=True, default='vaga.npg', null=True, upload_to=vagas.models.models_vagas.upload_to),
        ),
    ]
