# Generated by Django 3.2.15 on 2022-08-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0011_vagas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='escolaridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vagas.escolaridadevaga'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='faixa_salarial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='status',
            field=models.BooleanField(blank=True, default=True, help_text='Status da vaga', null=True),
        ),
    ]
