# Generated by Django 3.2.15 on 2022-08-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0013_auto_20220817_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='quantidade',
        ),
    ]
