# Generated by Django 3.2.15 on 2022-08-18 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0014_remove_vagas_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='QtdCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_candidatos', models.IntegerField(blank=True, default=0, null=True)),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('vaga_candidatada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vagas')),
            ],
        ),
    ]
