# Generated by Django 3.2.15 on 2022-08-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da empresa', max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='qtd_funcionario',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
