# Generated by Django 3.2.15 on 2022-08-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20220811_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='qtd_funcionario',
            field=models.IntegerField(blank=True, default=0, help_text='Quantidade de funcionarios', null=True),
        ),
    ]
