# Generated by Django 3.2.15 on 2022-08-21 04:00

from django.db import migrations, models
import empresas.models.models_empresa


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_qtd_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='foto',
            field=models.ImageField(blank=True, default='vaga.png', null=True, upload_to=empresas.models.models_empresa.upload_to),
        ),
    ]
