# Generated by Django 3.2.15 on 2022-08-12 02:05

import candidaturas.models.models_candidato
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_escolaridade_outros'),
        ('vagas', '0003_vagas_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default=candidaturas.models.models_candidato.gerar_codigo, editable=False, max_length=14, null=True, unique=True)),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('candidato', models.ManyToManyField(to='usuarios.ProfileUser')),
                ('vaga', models.ManyToManyField(to='vagas.Vagas')),
            ],
            options={
                'verbose_name': 'candidatura',
                'verbose_name_plural': 'candidaturas',
                'db_table': 'candidatura',
            },
        ),
    ]
