# Generated by Django 3.2.15 on 2022-08-21 05:36

import candidaturas.models.models_candidato
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0015_qtdcandidatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscolaridadeCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuatidadeCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(max_length=70)),
                ('quantidade_candidatos', models.IntegerField(blank=True, default=0, null=True)),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitosCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default=candidaturas.models.models_candidato.gerar_codigo, editable=False, max_length=14, null=True, unique=True)),
                ('requisitos', models.TextField(blank=True, max_length=2000, null=True)),
                ('escolhido', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_cadastro', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('escolaridade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidaturas.escolaridadecandidatura')),
                ('requisitos_adicionais', models.ManyToManyField(blank=True, null=True, to='candidaturas.RequisitosCandidatura')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vagas')),
            ],
            options={
                'verbose_name': 'candidatura',
                'verbose_name_plural': 'candidaturas',
                'db_table': 'candidatura',
            },
        ),
    ]
