# Generated by Django 3.2.15 on 2022-08-12 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_vagas_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidaturas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatura',
            name='candidato',
        ),
        migrations.AddField(
            model_name='candidatura',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='vaga',
        ),
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vagas.vagas'),
            preserve_default=False,
        ),
    ]
