# Generated by Django 3.2.15 on 2022-08-21 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidaturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='candidato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
