# Generated by Django 3.2.15 on 2022-08-12 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_vagas_empresa'),
        ('candidaturas', '0002_auto_20220811_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='vaga',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='vagas.vagas'),
        ),
    ]
