# Generated by Django 3.2.15 on 2022-08-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0003_alter_candidatura_candidato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatura',
            name='escolaridade',
        ),
    ]
