# Generated by Django 3.2.15 on 2022-08-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0005_vagas_tipo'),
        ('candidaturas', '0004_auto_20220812_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatura',
            name='vaga',
        ),
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='vagas.vagas'),
            preserve_default=False,
        ),
    ]
