# Generated by Django 3.2.15 on 2022-08-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0004_remove_candidatura_escolaridade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatura',
            name='requisitos_adicionais',
        ),
    ]
