# Generated by Django 3.2.15 on 2022-08-12 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vagas', '0005_vagas_tipo'),
        ('candidaturas', '0008_alter_candidatura_candidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='vaga',
        ),
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vagas.vagas'),
            preserve_default=False,
        ),
    ]
