# Generated by Django 3.2.15 on 2022-08-13 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0009_auto_20220812_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscolaridadeVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitosVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidatura',
            name='requisitos',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='escolaridade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidaturas.escolaridadevaga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatura',
            name='requisitos_adicionais',
            field=models.ManyToManyField(to='candidaturas.RequisitosVaga'),
        ),
    ]
