# Generated by Django 3.2.15 on 2022-08-13 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0011_auto_20220812_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatura',
            name='requisitos_adicionais',
        ),
        migrations.AddField(
            model_name='candidatura',
            name='requisitos_adicionais',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidaturas.requisitoscandidatura'),
            preserve_default=False,
        ),
    ]
