# Generated by Django 3.2.15 on 2022-08-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0012_auto_20220812_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='escolhido',
            field=models.BooleanField(default=False),
        ),
    ]
