# Generated by Django 3.2.15 on 2022-08-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0013_candidatura_escolhido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='escolaridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidaturas.escolaridadecandidatura'),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='requisitos_adicionais',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidaturas.requisitoscandidatura'),
        ),
    ]
