# Generated by Django 4.1 on 2022-08-15 18:56

from django.db import migrations, models
import django.utils.timezone
import vagas.models.models_vagas


class Migration(migrations.Migration):

    dependencies = [
        ("candidaturas", "0014_auto_20220812_2153"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vaga",
                    models.CharField(
                        max_length=70, verbose_name=vagas.models.models_vagas.Vagas
                    ),
                ),
                (
                    "quantidade_candidatos",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_cadastro", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
