# Generated by Django 4.1 on 2022-08-15 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidaturas", "0015_calculos"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Calculos",
            new_name="QuatidadeCandidatura",
        ),
    ]
