# Generated by Django 4.1 on 2022-08-15 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0009_remove_vagas_escolaridade_vagas_escolaridade"),
        ("candidaturas", "0016_rename_calculos_quatidadecandidatura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quatidadecandidatura",
            name="vaga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="vagas.vagas"
            ),
        ),
    ]
