# Generated by Django 4.1 on 2022-08-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0009_remove_vagas_escolaridade_vagas_escolaridade"),
        ("candidaturas", "0018_alter_quatidadecandidatura_vaga"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quatidadecandidatura",
            name="vaga",
        ),
        migrations.AddField(
            model_name="quatidadecandidatura",
            name="vaga",
            field=models.ManyToManyField(to="vagas.vagas"),
        ),
    ]
