# Generated by Django 4.1 on 2022-08-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidaturas", "0019_remove_quatidadecandidatura_vaga_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quatidadecandidatura",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
