# Generated by Django 4.1 on 2022-08-15 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vagas", "0009_remove_vagas_escolaridade_vagas_escolaridade"),
        ("candidaturas", "0020_alter_quatidadecandidatura_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quatidadecandidatura",
            name="vaga",
        ),
        migrations.AddField(
            model_name="quatidadecandidatura",
            name="vaga",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="vagas.vagas"
            ),
            preserve_default=False,
        ),
    ]
