# Generated by Django 4.1 on 2022-08-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidaturas", "0021_remove_quatidadecandidatura_vaga_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatura",
            name="requisitos_adicionais",
        ),
        migrations.AddField(
            model_name="candidatura",
            name="requisitos_adicionais",
            field=models.ManyToManyField(
                blank=True, null=True, to="candidaturas.requisitoscandidatura"
            ),
        ),
    ]
