# Generated by Django 4.1 on 2022-08-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidaturas", "0024_alter_quatidadecandidatura_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quatidadecandidatura",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
