# Generated by Django 3.2.15 on 2022-08-12 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escolaridade', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='escolaridade_user',
            field=models.ManyToManyField(to='usuarios.Escolaridade'),
        ),
    ]
