# Generated by Django 3.2.15 on 2022-08-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Escolaridade',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='escolaridade_user',
            field=models.CharField(blank=True, db_column='escolaridade_user', max_length=40, null=True),
        ),
    ]
